// frontend/src/app/features/landing/landing-page.component.ts
import { Component } from '@angular/core';
import { HeaderComponent } from './header.component';
import { HeroSectionComponent } from './hero-section.component';
import { AboutUsSectionComponent } from './about-us-section.component';
import { ServicesSectionComponent } from './services-section.component';
import { AiSectionComponent } from './ai-section.component';
import { ContactSectionComponent } from './contact-section.component';
import { FooterComponent } from './footer.component';

@Component({
  selector: 'app-landing-page',
  standalone: true,
  imports: [
    HeaderComponent,
    HeroSectionComponent,
    AboutUsSectionComponent,
    ServicesSectionComponent,
    AiSectionComponent,
    ContactSectionComponent,
    FooterComponent
  ],
  template: `
    <div class="min-h-screen bg-gray-100 flex flex-col">
      <app-header></app-header>
      <main class="flex-grow">
        <app-hero-section></app-hero-section>
        <app-about-us-section></app-about-us-section>
        <app-services-section></app-services-section>
        <app-ai-section></app-ai-section>
        <app-contact-section></app-contact-section>
      </main>
      <app-footer></app-footer>
    </div>
  `
})
export class LandingPageComponent {}

// frontend_react_backup/src/pages/Landing/LandingPage.jsx
// frontend/src/pages/Landing/LandingPage.jsx

import React from 'react';
import Header from './Header';
import HeroSection from './HeroSection';
import AboutUsSection from './AboutUsSection';
import ServicesSection from './ServicesSection';
import AISection from './AISection';
import ContactSection from './ContactSection';
import Footer from './Footer';

const LandingPage = () => {
    return (
        <div className="min-h-screen bg-gray-100 flex flex-col">
            <Header />
            <main className="flex-grow">
                <HeroSection />
                <AboutUsSection />
                <ServicesSection />
                <AISection />
                <ContactSection />
            </main>
            <Footer />
        </div>
    );
};

export default LandingPage;
